//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBCashRegistation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int id { get; set; }
        public string BillNo { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public double Total { get; set; }
        public double Discount { get; set; }
        public double NetAmount { get; set; }
        public string PhoneNumber { get; set; }
        public int SecID { get; set; }
        public double ServiceCharge { get; set; }
        public string PaymentType { get; set; }
    }
}
