//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBCashRegistation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public Nullable<int> Isloyal { get; set; }
        public string cashierIdenti { get; set; }
    }
}
