//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBCashRegistation
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodCAT
    {
        public int CATID { get; set; }
        public string CATName { get; set; }
    }
}
